# Generated by Django 4.0.6 on 2022-07-13 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.UUIDField(default='17b3a49957524af194cce7efaf6b5ab4', editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=100)),
                ('pwd_text', models.CharField(max_length=500)),
                ('pwd_md5', models.CharField(max_length=100)),
                ('pwd_sha', models.CharField(max_length=100)),
                ('pwd_sha256', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_login',
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.UUIDField(default='17b3a49957524af194cce7efaf6b5ab4', editable=False, primary_key=True, serialize=False)),
                ('street_name', models.CharField(max_length=200)),
                ('street_no', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=50)),
                ('coordinates_lat', models.FloatField()),
                ('coordinates_long', models.FloatField()),
                ('timezone_offset', models.TimeField()),
                ('timezone_desc', models.CharField(max_length=200)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.userlogin')),
            ],
            options={
                'db_table': 'user_location',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.UUIDField(default='17b3a49957524af194cce7efaf6b5ab4', editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('age', models.IntegerField(default=0)),
                ('reg_date', models.DateField(default=django.utils.timezone.now)),
                ('profile_l', models.URLField()),
                ('profile_m', models.URLField()),
                ('profile_t', models.URLField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.userlogin')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.UUIDField(default='17b3a49957524af194cce7efaf6b5ab4', editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('cell', models.CharField(max_length=20)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.userlogin')),
            ],
            options={
                'db_table': 'user_contact',
            },
        ),
    ]
